### PR TITLE
completed css-colors

### PR DESCRIPTION
**Pull request by Logisticx**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Close, but try to choose colors that more closely match the example:

---

image

**Review by TimelikeClosure — COMMENTED** [review]
@Logisticx Please add a screenshot of what your page looks like now

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
@Logisticx Please add a screenshot of what your page looks like now

**Comment by Logisticx** [comment]
image
Updated image

**Review by TimelikeClosure — APPROVED** [review]

**Pull request merged**
